server:
  port: 9999

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://129.211.88.191:3306/myblog?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: xxxxxxx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.huawei.l00379880: debug
  file: log/myblog-dev.log

